# Generated by Django 6.0.7 on 2026-07-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('PRIMARIO', 'Nivel Primario'), ('SECUNDARIO', 'Nivel Secundario')], max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
    ]
