# Generated by Django 6.0.7 on 2026-07-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0002_requisito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisito',
            name='nivel',
            field=models.CharField(choices=[('PRIMARIO', 'Solo Nivel Primario'), ('SECUNDARIO', 'Solo Nivel Secundario'), ('AMBOS', 'Ambos Niveles (General)')], default='AMBOS', max_length=20),
        ),
    ]
