# Generated by Django 6.0.7 on 2026-07-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0004_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosEscuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Instituto San Martín', max_length=150)),
                ('direccion', models.CharField(default='Av. Italia 1234, Corrientes', max_length=255)),
                ('telefono', models.CharField(default='0379-4123456', max_length=50)),
                ('whatsapp', models.CharField(default='3794123456', help_text='Número sin + ni espacios para el link de WhatsApp', max_length=50)),
                ('email', models.EmailField(default='contacto@institutosanmartin.edu.ar', max_length=254)),
                ('horario', models.CharField(default='Lunes a Viernes de 07:00 a 19:00 hs', max_length=150)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Datos de la Escuela',
                'verbose_name_plural': 'Datos de la Escuela',
            },
        ),
    ]
