# Generated by Django 6.0.7 on 2026-07-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0005_datosescuela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosescuela',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datosescuela',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='datosescuela',
            name='horario',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='datosescuela',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datosescuela',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Número sin + ni espacios para el link de WhatsApp', max_length=50, null=True),
        ),
    ]
