# Generated by Django 6.0.7 on 2026-07-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0007_preguntafrecuente'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosescuela',
            name='frase',
            field=models.CharField(blank=True, help_text='Frase institucional o lema de la escuela', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datosescuela',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo de la escuela', null=True, upload_to='escuela/logos/'),
        ),
    ]
