# Generated by Django 6.0.7 on 2026-07-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0008_datosescuela_frase_datosescuela_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostulacionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=50)),
                ('nivel_interes', models.CharField(choices=[('MATERNAL', 'Nivel Maternal'), ('INICIAL', 'Nivel Inicial'), ('PRIMARIO', 'Nivel Primario'), ('SECUNDARIO', 'Nivel Secundario'), ('VARIOS', 'Varios / General')], default='PRIMARIO', max_length=20)),
                ('area_materia', models.CharField(help_text='Ej: Matemática, Maestra de Grado, Inglés, etc.', max_length=100)),
                ('cv', models.FileField(help_text='Adjuntar archivo PDF o Word', upload_to='cvs/')),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('revisado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Postulación Docente',
                'verbose_name_plural': 'Postulaciones Docentes',
            },
        ),
    ]
