# Generated by Django 6.0.7 on 2026-07-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0009_postulaciondocente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Subir archivo de imagen para la noticia', null=True, upload_to='noticias/'),
        ),
    ]
