# Generated by Django 6.0.7 on 2026-07-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0010_remove_noticia_imagen_url_noticia_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarruselInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título (Opcional)')),
                ('subtitulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtítulo / Bajada (Opcional)')),
                ('imagen', models.ImageField(upload_to='carrusel/', verbose_name='Imagen del Carrusel')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición (0, 1, 2...)')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Mostrar en la web?')),
            ],
            options={
                'verbose_name': 'Imagen del Carrusel',
                'verbose_name_plural': 'Carrusel del Inicio',
                'ordering': ['orden'],
            },
        ),
    ]
