# Generated by Django 6.0.7 on 2026-07-27 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0011_carruselinicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='carruselinicio',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrusel', to='escuela.datosescuela'),
        ),
    ]
