# Generated by Django 6.0.7 on 2026-07-27 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0012_carruselinicio_escuela'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carruselinicio',
            name='escuela',
        ),
    ]
