# Generated by Django 6.0.7 on 2026-07-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0013_remove_carruselinicio_escuela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carruselinicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='carrusel/', verbose_name='Imagen del Carrusel'),
        ),
    ]
