# Generated by Django 6.0.7 on 2026-07-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0014_alter_carruselinicio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosescuela',
            name='hero_boton_principal_text',
            field=models.CharField(blank=True, default='VER REQUISITOS DE INSCRIPCIÓN', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='datosescuela',
            name='hero_boton_principal_url',
            field=models.CharField(blank=True, default='/requisitos/', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datosescuela',
            name='hero_boton_secundario_text',
            field=models.CharField(blank=True, default='CONTACTANOS', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='datosescuela',
            name='hero_boton_secundario_url',
            field=models.CharField(blank=True, default='/contacto/', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datosescuela',
            name='hero_imagen',
            field=models.ImageField(blank=True, help_text='Imagen principal del inicio', null=True, upload_to='escuela/hero/'),
        ),
        migrations.AddField(
            model_name='datosescuela',
            name='hero_subtitulo',
            field=models.TextField(blank=True, default='Propuesta pedagógica comprometida con una formación humana de calidad desde Nivel Maternal hasta Primario.', null=True),
        ),
        migrations.AddField(
            model_name='datosescuela',
            name='hero_tag',
            field=models.CharField(blank=True, default='Inscripciones Abiertas', help_text='Texto corto del banner principal', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='datosescuela',
            name='hero_titulo',
            field=models.CharField(blank=True, default='EDUCACIÓN INTEGRAL Y DE EXCELENCIA', max_length=150, null=True),
        ),
    ]
