# Generated by Django 6.0.7 on 2026-07-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0015_datosescuela_hero_boton_principal_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('icono', models.CharField(blank=True, help_text='Ejemplo: ✨, 📚, 🏫', max_length=40, null=True, verbose_name='Icono')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Mostrar en la web?')),
            ],
            options={
                'verbose_name': 'Bloque de Inicio',
                'verbose_name_plural': 'Bloques de Inicio',
                'ordering': ['orden'],
            },
        ),
    ]
