# Generated by Django 6.0.7 on 2026-07-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0016_bloqueinicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(help_text='Ej: Directora, Docente de Inglés, etc.', max_length=100)),
                ('nivel', models.CharField(choices=[('DIRECTIVO', 'Equipo Directivo'), ('INICIAL', 'Nivel Inicial / Maternal'), ('PRIMARIO', 'Nivel Primario'), ('ESPECIALIDAD', 'Especialidades / Talleres')], default='PRIMARIO', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='docentes/')),
                ('orden', models.IntegerField(default=0, help_text='Para ordenar quién sale primero')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
