# Generated by Django 6.0.7 on 2026-07-29 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0017_docente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloqueInicio',
        ),
    ]
