# Generated by Django 6.0.7 on 2026-07-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0018_delete_bloqueinicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisito',
            name='nivel',
            field=models.CharField(choices=[('INICIAL', 'Nivel Inicial'), ('PRIMARIO', 'Nivel Primario'), ('MEDIO', 'Nivel Medio'), ('AMBOS', 'Todos los Niveles (General)')], default='AMBOS', max_length=20),
        ),
    ]
